### ISSUE TITLE
Error while installation via manager

### ISSUE THREAD

**Issue by proplab** [Web-Ex-Machina/contao-portfolio#14]
There is an error while installing via the manager (Contao 4.4.49)

`An error occurred while executing the "cache:warmup" command: 11:47:16 ERROR [console] Error thrown while running command "cache:warmup --env=prod". Message: "syntax error, unexpected ')'" ["exception" => ParseError { …}, "command" => "cache:warmup --env=prod","message" => "syntax error, unexpected ')'"] In tl_wem_portfolio_category_item.php line168:      Parse error: syntax error, unexpected ')'`

**Comment by LupusVII** [comment]
Hi! 
To be honest, the repo is not really available for a public use, so if you use a 4.9 version of Contao, it will work, but if you have to use a 4.4, I recommand using another module, or to be veeeery patient because I cannot fix it right now. :/
